export const contentTypes = [
  'application/json',
  'application/ld+json',
  'application/x-yaml',
  'application/xml',
  'image/avif',
  'image/gif',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
  'image/tiff',
  'image/webp',
  'text/css',
  'text/csv',
  'text/html',
  'text/plain',
  'text/xml',
  'video/mp4',
  'video/mpeg',
  'video/webm',
] as const;
